blank_issues_enabled: false
contact_links:
  - name: Ory Hydra Login, Logout And Consent Node Example Forum
    url: https://github.com/ory/hydra-login-consent-node/discussions
    about: Please ask and answer questions here, show your implementations and discuss ideas.
  - name: Ory Chat
    url: https://www.ory.sh/chat
    about: Hang out with other Ory community members to ask and answer questions.
  - name: Ory Support for Business
    url: https://github.com/ory/open-source-support/blob/master/README.md
    about: Buy professional support for Ory Hydra Login, Logout And Consent Node Example.
