name: test and release

on:
  push:
    tags:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 11.10
      - name: restore cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: v1-dependencies-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            v1-dependencies-
      - name: install dependencies
        run: npm ci
      - name: configure npm token
        run:
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >
          ~/.npmrc
      - name: build project
        run: npm run build

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 23.7.0
      - name: restore cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: v1-dependencies-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            v1-dependencies-
      - name: install dependencies
        run: npm ci
      - name: configure npm token
        run:
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >
          ~/.npmrc
      - name: set package version
        run: npm version -f --no-git-tag-version "${GITHUB_REF#refs/tags/}"
      - name: publish package
        run: npm publish --access public
